//
// Copyright (c) 2023 Klemens Morgenstern (klemens.morgenstern@gmx.net)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

// STATE: Stream of consciousness


ifndef::asio-doc[]
:asio_doc: https://www.boost.org/doc/libs/develop/doc/html/boost_asio
endif::asio-doc[]

ifndef::asio-ref[]
:asio-ref: {asio_doc}/reference
endif::asio-ref[]

== Writing to files

NOTE: File IO only works on windows or linux when `BOOST_ASIO_HAS_IO_URING` is defined & `liburing`` installed.


[source,cpp]
----
include::./code/02_sync_write_file_throw.cpp[tag=example]
----
<1> The ((execution context))
<2> The file io-object for stream reading (i.e. non-random access). The constructor opens the file with the given flags and may throw a `system_error`.
<3> Perform the ((write_some)) operation 

Write streams in asio have a `write_some`, not `write` function. 
Instead of writing all the data, asio writes as much data is can be done in a single system call. (This is more important asynchronous code). The size of the actually written data depends on the system API and settings like buffer sizes. The user of a `write_some` function therefor needs to consider the return value
telling him how much data was written. Asio provides algorithms like <<write>> for that, which will be discussed later.

The first parameter to the `write_some` function is a <<((ConstBufferSequence))>>.

// TODO: DO we put the sequence spec here?


A write operation may produce an error AND write data. In the case of the {asio-ref}/stream_file.html[`asio::stream_file`] this can happen when the operation reached the end of a file. Thus using the throwing overload my lose data.


As typical for synchronous operations, the non-throwing overload adds a reference to `error_code` at the end to handle operation errors.

[source,cpp]
----
include::./code/02_sync_write_file_ec.cpp[tag=example]
----
<1> Initiate the io-object without opening the file, to avoid exceptions.
<2> Open the file with the non-throwing overload.
<3> Check that the `open` function didn't produce an error before writing.
<4> Perform the write the non-throwing overload.
